name: Main Merge Group Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  merge_group:
    branches: main

jobs:
    validate:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - run: echo "Validating..."
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."
            - run: exit 1