name: Main PR Workflow

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview-${{ github.event.pull_request.number }}
      url: https://preview-${{ github.event.pull_request.number }}.example.com
    steps:
      - run: echo "Preview URL: https://preview-${{ github.event.pull_request.number }}.example.com"
