name: Main Push Workflow

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

on:
  push:
    branches: main

jobs:
    deploy-to-staging:
        environment: Staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."

    deploy-to-production:
        environment: Production
        needs: deploy-to-staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."