name: Main PR Workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  pull_request:
    branches: main

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Validating..."